create endpoint POST /register in class UserController and implement …
green-fox-academy/godess-tribes-backend pull request #1
Opened 2019-05-12 22:14 UTC by ZetenyiEmese

Megcsináltam a POST /register endpointot, és minden hozzátartozó cuccot, leteszteltem Postmannel (nekem ok), kérlek nézzétek át. Emese

2019-05-13 12:09 UTC, balazsbarni requested changes

2019-05-13 12:09 UTC, balazsbarni commented on build.gradle
> +
please remove the empty line

2019-05-13 12:09 UTC, balazsbarni commented on src/main/java/com/greenfoxacademy/goddesstribesbackend/controllers/UserController.java
> +      return ResponseEntity.status(400).body(new ErrorMessage("Username is already taken."));
409 status by APIdocs and would be nice to respond : "Zolika -as username taken", ore something like that

2019-05-13 12:09 UTC, balazsbarni commented on src/main/java/com/greenfoxacademy/goddesstribesbackend/controllers/UserController.java
> +    } else {
else is needed?

2019-05-13 12:09 UTC, balazsbarni commented on src/main/java/com/greenfoxacademy/goddesstribesbackend/security/jwt/JWTAuthenticationFilter.java
> +
please remove the empty line

2019-05-13 12:09 UTC, balazsbarni commented on src/main/java/com/greenfoxacademy/goddesstribesbackend/security/jwt/JWTUtility.java
> +
not needed

2019-05-13 12:09 UTC, balazsbarni commented on src/main/java/com/greenfoxacademy/goddesstribesbackend/security/jwt/JWTUtility.java
> +
not needed

2019-05-13 12:09 UTC, balazsbarni commented on src/main/java/com/greenfoxacademy/goddesstribesbackend/security/jwt/JWTUtility.java
> +}
empty line after the last line

2019-05-13 13:22 UTC, ZetenyiEmese commented on build.gradle
> +
Done.

2019-05-13 13:22 UTC, ZetenyiEmese commented on src/main/java/com/greenfoxacademy/goddesstribesbackend/controllers/UserController.java
> +      return ResponseEntity.status(400).body(new ErrorMessage("Username is already taken."));
Done

2019-05-13 13:23 UTC, ZetenyiEmese commented on src/main/java/com/greenfoxacademy/goddesstribesbackend/controllers/UserController.java
> +    } else {
No, else is not needed. It was removed.

2019-05-13 13:26 UTC, ZetenyiEmese commented on src/main/java/com/greenfoxacademy/goddesstribesbackend/security/jwt/JWTAuthenticationFilter.java
> +
Done.

2019-05-13 13:27 UTC, ZetenyiEmese commented on src/main/java/com/greenfoxacademy/goddesstribesbackend/security/jwt/JWTUtility.java
> +
Ok, removed.

2019-05-13 13:27 UTC, ZetenyiEmese commented on src/main/java/com/greenfoxacademy/goddesstribesbackend/security/jwt/JWTUtility.java
> +
Ok, removed.

2019-05-13 13:28 UTC, ZetenyiEmese commented on src/main/java/com/greenfoxacademy/goddesstribesbackend/security/jwt/JWTUtility.java
> +}
I always add an empty line after the last line, but it is not visible on github...sorry

2019-05-14 07:19 UTC, balazsbarni approved these changes

2019-05-14 13:03 UTC, symunona approved these changes
The one and only thing I found, was the name of the branch :)
We will have a chat about that, it's good to go now!

2019-05-14 13:38 UTC, merged