Tgb55 unittest kingdomservice
green-fox-academy/godess-tribes-backend pull request #26
Opened 2019-06-13 22:46 UTC by ZetenyiEmese

Unit tesztek a KingdomService metódusaihoz (időhiány miatt nem az összeshez...)

2019-06-14 09:02 UTC, balazsbarni requested changes
Szep munka, azal a kikommenetelt resszel mi a helyzet?

2019-06-14 09:02 UTC, balazsbarni commented on src/main/java/com/greenfoxacademy/goddesstribesbackend/security/WebSecurityConfig.java
> +//  }
ezt miert?

2019-06-14 10:47 UTC, szutsj commented on src/main/java/com/greenfoxacademy/goddesstribesbackend/security/WebSecurityConfig.java
> +//  }
Emese, próbáld ki, légyszi, azt a megoldást, amit a próba branchbe tettem, szerintem ez megoldja az ide-oda ki-bekommentelést.

2019-06-14 10:48 UTC, szutsj commented on src/main/java/com/greenfoxacademy/goddesstribesbackend/security/WebSecurityConfig.java
> +//  }
Barninak válaszként: Emese gépén a fenti bean nélkül nem fut a teszt, a bean-nel viszont nem megy az app, és pl. Ági gépén a teszt sem. Szóval ezért van ide-oda változgatva...

2019-06-14 16:27 UTC, ZetenyiEmese commented
Kipróbáltam, működik, köszi Judit.

2019-06-14 16:57 UTC, szutsj approved these changes

2019-06-17 07:20 UTC, balazsbarni approved these changes

2019-06-18 23:29 UTC, merged